name: Rails

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Build the Docker image
        run: |
          docker-compose build
          docker-compose run --rm web bundle install --jobs 4 --retry 3

      - name: Test
        run: docker-compose run --rm web rspec
